# Generated by Django 5.0.14 on 2025-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_estudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantelogin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiantelogin',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiantelogin',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
