# Generated by Django 5.0.14 on 2025-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_estudiantelogin_email_estudiantelogin_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantelogin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiantelogin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
