# Generated by Django 5.0.14 on 2025-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_estudiantelogin_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantelogin',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
